"""empty message

Revision ID: 67d7f6278369
Revises: f37d2dd35110
Create Date: 2021-11-23 14:52:07.689545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d7f6278369'
down_revision = 'f37d2dd35110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_account_branch_uc', 'member', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_account_branch_uc', 'member', type_='unique')
    # ### end Alembic commands ###
