"""empty message

Revision ID: ac8bc92683ba
Revises: a099e2ef5e13
Create Date: 2021-11-26 15:40:09.770069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8bc92683ba'
down_revision = 'a099e2ef5e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_account_email_unique', 'member', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_account_email_unique', 'member', type_='unique')
    # ### end Alembic commands ###
