"""empty message

Revision ID: d9a00fa087ee
Revises: ee52e5a0c99c
Create Date: 2021-11-27 18:33:08.121188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9a00fa087ee'
down_revision = 'ee52e5a0c99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('member_role_fkey', 'member', type_='foreignkey')
    op.drop_column('member', 'role')
    op.add_column('role', sa.Column('member', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'role', 'member', ['member'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'member')
    op.add_column('member', sa.Column('role', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('member_role_fkey', 'member', 'role', ['role'], ['id'])
    # ### end Alembic commands ###
