"""empty message

Revision ID: f21b347b57a1
Revises: 47c43c12bcd3
Create Date: 2021-11-27 23:50:22.389345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f21b347b57a1'
down_revision = '47c43c12bcd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('role', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('member_member_fkey', 'member', type_='foreignkey')
    op.create_foreign_key(None, 'member', 'role', ['role'], ['id'])
    op.drop_column('member', 'member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('member', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.create_foreign_key('member_member_fkey', 'member', 'member', ['member'], ['id'])
    op.drop_column('member', 'role')
    # ### end Alembic commands ###
