"""empty message

Revision ID: f37d2dd35110
Revises: 
Create Date: 2021-11-23 14:42:43.184259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37d2dd35110'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_email_unique_constraint', 'member', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_email_unique_constraint', 'member', type_='unique')
    # ### end Alembic commands ###
